# ---------------------------------------------------------
# ------------------- ADC 1 AD9240 ------------------------
# ---------------------------------------------------------
set_property PACKAGE_PIN C17 [get_ports {adc1_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[13]}]
set_property PACKAGE_PIN C18 [get_ports {adc1_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[12]}]
set_property PACKAGE_PIN B16 [get_ports {adc1_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[11]}]
set_property PACKAGE_PIN B17 [get_ports {adc1_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[10]}]
set_property PACKAGE_PIN B21 [get_ports {adc1_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[9]}]
set_property PACKAGE_PIN B22 [get_ports {adc1_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[8]}]
set_property PACKAGE_PIN A22 [get_ports {adc1_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[7]}]
set_property PACKAGE_PIN A21 [get_ports {adc1_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[6]}]
set_property PACKAGE_PIN B15 [get_ports {adc1_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[5]}]
set_property PACKAGE_PIN C15 [get_ports {adc1_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[4]}]
set_property PACKAGE_PIN A17 [get_ports {adc1_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[3]}]
set_property PACKAGE_PIN A16 [get_ports {adc1_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[2]}]
set_property PACKAGE_PIN A19 [get_ports {adc1_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[1]}]
set_property PACKAGE_PIN C22 [get_ports {adc1_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_in[0]}]
set_property PACKAGE_PIN D22 [get_ports adc1_otr]
set_property IOSTANDARD LVCMOS33 [get_ports adc1_otr]
# ------------------- ADC THS7001 -------------------------
set_property PACKAGE_PIN G19 [get_ports {adc1_gain[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_gain[0]}]
set_property PACKAGE_PIN F19 [get_ports {adc1_gain[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_gain[1]}]
set_property PACKAGE_PIN E19 [get_ports {adc1_gain[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc1_gain[2]}]

# ---------------------------------------------------------
# ------------------- ADC 2 AD9240 ------------------------
# ---------------------------------------------------------
set_property PACKAGE_PIN L17 [get_ports {adc2_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[13]}]
set_property PACKAGE_PIN K19 [get_ports {adc2_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[12]}]
set_property PACKAGE_PIN M17 [get_ports {adc2_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[11]}]
set_property PACKAGE_PIN K20 [get_ports {adc2_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[10]}]
set_property PACKAGE_PIN K21 [get_ports {adc2_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[9]}]
set_property PACKAGE_PIN B19 [get_ports {adc2_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[8]}]
set_property PACKAGE_PIN B20 [get_ports {adc2_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[7]}]
set_property PACKAGE_PIN D20 [get_ports {adc2_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[6]}]
set_property PACKAGE_PIN E15 [get_ports {adc2_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[5]}]
set_property PACKAGE_PIN C20 [get_ports {adc2_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[4]}]
set_property PACKAGE_PIN D15 [get_ports {adc2_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[3]}]
set_property PACKAGE_PIN G20 [get_ports {adc2_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[2]}]
set_property PACKAGE_PIN G21 [get_ports {adc2_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[1]}]
set_property PACKAGE_PIN E21 [get_ports {adc2_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_in[0]}]
set_property PACKAGE_PIN P21 [get_ports adc2_otr]
set_property IOSTANDARD LVCMOS33 [get_ports adc2_otr]
# ------------------- ADC THS7001 -------------------------
set_property PACKAGE_PIN F18 [get_ports {adc2_gain[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_gain[0]}]
set_property PACKAGE_PIN D21 [get_ports {adc2_gain[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_gain[1]}]
set_property PACKAGE_PIN E18 [get_ports {adc2_gain[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc2_gain[2]}]

set_property PACKAGE_PIN E20 [get_ports adc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk]

# ---------------------------------------------------------
# ------------------- DAC AD9764 --------------------------
# ---------------------------------------------------------
set_property PACKAGE_PIN P22 [get_ports {dac_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[0]}]
set_property PACKAGE_PIN N19 [get_ports {dac_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[1]}]
set_property PACKAGE_PIN N20 [get_ports {dac_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[2]}]
set_property PACKAGE_PIN J21 [get_ports {dac_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[3]}]
set_property PACKAGE_PIN L21 [get_ports {dac_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[4]}]
set_property PACKAGE_PIN J22 [get_ports {dac_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[5]}]
set_property PACKAGE_PIN L22 [get_ports {dac_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[6]}]
set_property PACKAGE_PIN J18 [get_ports {dac_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[7]}]
set_property PACKAGE_PIN K18 [get_ports {dac_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[8]}]
set_property PACKAGE_PIN R20 [get_ports {dac_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[9]}]
set_property PACKAGE_PIN R19 [get_ports {dac_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[10]}]
set_property PACKAGE_PIN R21 [get_ports {dac_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[11]}]
set_property PACKAGE_PIN T19 [get_ports {dac_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[12]}]
set_property PACKAGE_PIN P20 [get_ports {dac_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[13]}]
set_property PACKAGE_PIN M19 [get_ports dac_clk]
set_property IOSTANDARD LVCMOS33 [get_ports dac_clk]
set_property PACKAGE_PIN M20 [get_ports {dac_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sel[0]}]
set_property PACKAGE_PIN N22 [get_ports {dac_rst[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_rst[0]}]


# -------- CONTROL ---------------
set_property PACKAGE_PIN T22 [get_ports otr1_out]
set_property IOSTANDARD LVCMOS33 [get_ports otr1_out]
set_property PACKAGE_PIN T21 [get_ports otr2_out]
set_property IOSTANDARD LVCMOS33 [get_ports otr2_out]


set_property SLEW SLOW [get_ports adc1_clk]
set_property SLEW SLOW [get_ports adc2_clk]
